### ISSUE TITLE
Manual trigger: Button on PR page

### ISSUE THREAD

**Issue by avikalpg** [vibinex/chrome-extension#103]
Currently, the UX for manually triggering Vibinex on a pull request is sub-optimal. The user has to copy the link of the pull request (which also has to be the root link of the pull request), paste it into the popup window (right next to the "Logout" button) and then click "Trigger".

A much better UX would be to have a button on the pull request page that can just be clicked to trigger Vibinex. 

Optional: Show different states of the button:
- Default: The button is ready to be clicked with the Vibinex refresh symbol, and the tooltip text "Process this PR on Vibinex".
- Highlighted: If the pull request is not processed even once before, change the styling of the button to highlight it more.
- On Click: As soon as the user clicks the button, it should become `disabled` and the text should change to "Triggering..."
- Processing: Once the trigger is successful, the button should still be disabled, but the color should change to a shade of green and the text should change to "Processing...".
- Done: Once the `hunks` table row for the pull request has a `last_modified_at` timestamp greater than the time of the click, we can change the text of the button to "Done!". Then we can either refresh the page or just trigger the UI update function again. The button should change back to the "Default" state once the UI is updated.

**Comment by harith-aaron** [comment]
Hi @avikalpg  , I am ready to work on it can you assign me now?
